<?php
	$routes = [
		'home',
		'login',
		'loginaction',
		'signup',
		'signupaction',
		'logoutaction',
		'rememberuser',
		'rememberuseraction',
		'userprofile',
		'usersettings',
		'usersettingsaction',
		'guestsettings',
		'guestsettingsaction',
		'dashboard',
		'error'
	];
?>